baseURL = "https://dullkingsman.github.io/dpg/"
title = "DPG — Declarative PG"
enableRobotsTXT = true
publishDir = "../internal/docssite/public"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
  proxy = "https://proxy.golang.org,direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"
