name: CI / Plugins

on:
  workflow_call:

jobs:
  helix:
    name: Helix
    uses: ./.github/workflows/ci-helix.yml

  idea:
    name: IntelliJ
    uses: ./.github/workflows/ci-idea.yml

  nvim:
    name: Neovim
    uses: ./.github/workflows/ci-nvim.yml

  vscode:
    name: VS Code
    uses: ./.github/workflows/ci-vscode.yml
