name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dpg:
    name: DPG core
    uses: ./.github/workflows/ci-dpg.yml

  lang:
    name: Language tools
    uses: ./.github/workflows/ci-lang.yml

  plugins:
    name: Editor plugins
    uses: ./.github/workflows/ci-plugins.yml
