name: Editor / IntelliJ

on:
  push:
    branches: [master]
    paths:
      - "editors/idea/**"
  pull_request:
    branches: [master]
    paths:
      - "editors/idea/**"

jobs:
  idea:
    name: JetBrains plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build plugin
        working-directory: editors/idea
        run: ./gradlew build verifyPlugin --no-daemon
